version: '3.6'
services:
  postgres:
    image: smartodo
    container_name: smartodo
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - ../../.env
    volumes:
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres-db:
